# Generated by Django 5.0 on 2024-08-20 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_realizacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CampanhaEleitoral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_registro', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('candidato', models.CharField(choices=[('V', 'Vereador'), ('P', 'Prefeito')], max_length=15)),
                ('partido', models.CharField(choices=[('UB', 'UB'), ('PMDB', 'PMDB'), ('PSDB', 'PSDB'), ('PL', 'PL'), ('PT', 'PT')], max_length=15)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('funcao', models.CharField(choices=[('Gerente', 'Gerente'), ('Cordenador', 'Cordenador'), ('Colaborador', 'Colaborador'), ('Cabo Eleitoral', 'Cabo Eleitoral'), ('Administrativo', 'Administrativo'), ('Auxiliar', 'Auxiliar'), ('Evangelista', 'Evangelista')], max_length=20)),
                ('tipo', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Ambos', 'Ambos')], max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ibge', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('GO', 'GOIAS'), ('DF', 'DISTRITO FEDERAL')], max_length=20)),
                ('populacao', models.IntegerField()),
                ('area_km2', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('densidade_demografica', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('idhm', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('receita_realizada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('despesa_realizada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pib_percapita', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeGoverno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCampanha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Planfeto', 'Planfleto'), ('Adesivo', 'Adesivo'), ('Sitru', 'Sitru'), ('Banner', 'Banner'), ('Brinde', 'Brinde'), ('Santinho', 'Santinho'), ('Santinho casado', 'Santinho Casado')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.campanhaeleitoral')),
            ],
        ),
        migrations.CreateModel(
            name='AplicacaoMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_aplicacao', models.CharField(choices=[('Comite', 'Comite'), ('Pre-Posto', 'Pre-posto'), ('Acao', 'Acao'), ('Externo', 'Externo')], default='Comite', max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('foto_aplicao', models.ImageField(blank=True, null=True, upload_to='acao_fotos/')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ce2024.equipe')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.materialcampanha')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='ce2024.localarmazenamento')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='ce2024.localarmazenamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.materialcampanha')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ce2024.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('regional', models.IntegerField()),
                ('populacao', models.IntegerField()),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitacoes', models.IntegerField()),
                ('familias', models.IntegerField()),
                ('bairros', models.IntegerField()),
                ('classe', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa'), ('Entusiasta', 'Entusiasta')], max_length=15)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes', to='ce2024.municipio')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('populacao', models.IntegerField(default=0)),
                ('area_km2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('habitacoes', models.IntegerField(default=0)),
                ('familias', models.IntegerField(default=0)),
                ('quantidade_ruas', models.IntegerField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('classe', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa'), ('Entusiasta', 'Entusiasta')], default='Media', max_length=15)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='ce2024.municipio')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiao', to='ce2024.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeCampanha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('COM', 'Comício'), ('PAN', 'Panfletagem'), ('CAR', 'Carreata'), ('VIS', 'Visita Domiciliar'), ('COR', 'Visita Corporativa'), ('REU', 'Reuniao Politica'), ('PUB', 'Evento Publico'), ('PRI', 'Evento Privado')], max_length=3)),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('numero_participantes', models.IntegerField()),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='ce2024.bairro')),
                ('agendado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='ce2024.equipe')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='ce2024.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField()),
                ('quantidade_aprovada', models.PositiveIntegerField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Negada', 'Negada'), ('Entregue', 'Entregue')], default='Pendente', max_length=10)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('local_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.localarmazenamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.materialcampanha')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEleitoral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_eleitorais', to='ce2024.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contato', models.CharField(max_length=100)),
                ('perfil_eleitoral', models.CharField(choices=[('Apoiador', 'Apoiador'), ('Indeciso', 'Indeciso'), ('Opositor', 'Opositor'), ('Entusiasta', 'Entusiasta'), ('Colaborador', 'Colaborador')], max_length=15)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleitores', to='ce2024.regiao')),
                ('zona_eleitoral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleitores', to='ce2024.zonaeleitoral')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.localarmazenamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ce2024.materialcampanha')),
            ],
            options={
                'unique_together': {('material', 'local')},
            },
        ),
    ]
