# Generated by Django 5.1 on 2024-08-18 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampanhaEleitoral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_registro', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('candidato', models.CharField(choices=[('V', 'Vereador'), ('P', 'Prefeito')], max_length=15)),
                ('partido', models.CharField(choices=[('UB', 'UB'), ('PMDB', 'PMDB'), ('PSDB', 'PSDB'), ('PL', 'PL'), ('PT', 'PT')], max_length=15)),
                ('numero', models.PositiveIntegerField(default=0)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalArmazenamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCampanha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Planfeto', 'Planfleto'), ('Adesivo', 'Adesivo'), ('Sitru', 'Sitru'), ('Banner', 'Banner'), ('Brinde', 'Brinde'), ('Santinho', 'Santinho'), ('Santinho casado', 'Santinho Casado')], max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.campanhaeleitoral')),
            ],
        ),
    ]
