# Generated by Django 5.0 on 2024-08-18 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0002_alter_localarmazenamento_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_registro', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('funcao', models.CharField(choices=[('Gerente', 'Gerente'), ('Cordenador', 'Cordenador'), ('Colaborador', 'Colaborador'), ('Cabo Eleitoral', 'Cabo Eleitoral')], max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='cego47700.localarmazenamento')),
                ('local_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='cego47700.localarmazenamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.materialcampanha')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cego47700.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_solicitada', models.PositiveIntegerField()),
                ('quantidade_aprovada', models.PositiveIntegerField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Negada', 'Negada'), ('Entregue', 'Entregue')], default='Pendente', max_length=10)),
                ('local_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.localarmazenamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.materialcampanha')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.localarmazenamento')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.materialcampanha')),
            ],
            options={
                'unique_together': {('material', 'local')},
            },
        ),
    ]
