# Generated by Django 5.0 on 2024-08-18 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0003_equipe_movimentacaomaterial_solicitacaomaterial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='localarmazenamento',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentacaomaterial',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimentacaomaterial',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacaomaterial',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitacaomaterial',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campanhaeleitoral',
            name='atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
