# Generated by Django 5.0 on 2024-08-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0004_equipe_atualizado_equipe_criado_estoque_atualizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='nome_registro',
        ),
    ]
