# Generated by Django 5.0 on 2024-08-18 23:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0005_remove_equipe_nome_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ibge', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('populacao', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='tipo',
            field=models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa'), ('Ambos', 'Ambos')], default=datetime.datetime(2024, 1, 1, 0, 0), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipe',
            name='funcao',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Cordenador', 'Cordenador'), ('Colaborador', 'Colaborador'), ('Cabo Eleitoral', 'Cabo Eleitoral'), ('Administrativo', 'Administrativo'), ('Auxiliar', 'Auxiliar'), ('Evangelista', 'Evangelista')], max_length=20),
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('populacao', models.IntegerField()),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitacoes', models.IntegerField()),
                ('familias', models.IntegerField()),
                ('bairros', models.IntegerField()),
                ('geocoordenadas', models.JSONField()),
                ('classe', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa'), ('Entusiasta', 'Entusiasta')], max_length=15)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioes', to='cego47700.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeCampanha',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('COM', 'Comício'), ('PAN', 'Panfletagem'), ('CAR', 'Carreata'), ('VIS', 'Visita Domiciliar'), ('COR', 'Visita Corporativa'), ('REU', 'Reuniao Politica'), ('PUB', 'Evento Publico'), ('PRI', 'Evento Privado')], max_length=3)),
                ('data_hora', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('numero_participantes', models.IntegerField()),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='cego47700.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaEleitoral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_eleitorais', to='cego47700.regiao')),
            ],
        ),
        migrations.CreateModel(
            name='Eleitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contato', models.CharField(max_length=100)),
                ('perfil_eleitoral', models.CharField(choices=[('Apoiador', 'Apoiador'), ('Indeciso', 'Indeciso'), ('Opositor', 'Opositor'), ('Entusiasta', 'Entusiasta'), ('Colaborador', 'Colaborador')], max_length=15)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('tiktok', models.URLField(blank=True, max_length=255, null=True)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleitores', to='cego47700.regiao')),
                ('zona_eleitoral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleitores', to='cego47700.zonaeleitoral')),
            ],
        ),
    ]
