# Generated by Django 5.0 on 2024-08-18 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0006_municipio_equipe_tipo_alter_equipe_funcao_regiao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='densidade_demografica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='despesa_realizada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='idhm',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='pib_percapita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='receita_realizada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.CharField(choices=[('GO', 'GOIAS'), ('DF', 'DISTRITO FEDERAL')], max_length=20),
        ),
    ]
