# Generated by Django 5.0 on 2024-08-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0007_municipio_area_km2_municipio_densidade_demografica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='densidade_demografica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='despesa_realizada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='idhm',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='pib_percapita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='receita_realizada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
