# Generated by Django 5.0 on 2024-08-18 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0009_alter_municipio_area_km2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('populacao', models.IntegerField()),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitacoes', models.IntegerField()),
                ('familias', models.IntegerField()),
                ('quantidade_ruas', models.IntegerField()),
                ('geocoordenadas', models.JSONField()),
                ('classe', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa'), ('Entusiasta', 'Entusiasta')], max_length=15)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio', to='cego47700.municipio')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiao', to='cego47700.regiao')),
            ],
        ),
    ]
