# Generated by Django 5.0 on 2024-08-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0010_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiao',
            name='geocoordenadas',
            field=models.JSONField(null=True),
        ),
    ]
