# Generated by Django 5.0 on 2024-08-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0011_alter_regiao_geocoordenadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiao',
            name='geocoordenadas',
        ),
    ]
