# Generated by Django 5.0 on 2024-08-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0012_remove_regiao_geocoordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiao',
            name='regional',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
