# Generated by Django 5.0 on 2024-08-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0013_regiao_regional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regiao',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='bairro',
            name='geocoordenadas',
        ),
        migrations.AddField(
            model_name='bairro',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bairro',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
