# Generated by Django 5.0 on 2024-08-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0014_alter_regiao_options_remove_bairro_geocoordenadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bairro',
            name='area_km2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='classe',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baixa', 'Baixa'), ('Entusiasta', 'Entusiasta')], default='Media', max_length=15),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='familias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='habitacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='populacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='quantidade_ruas',
            field=models.IntegerField(default=0),
        ),
    ]
