# Generated by Django 5.0 on 2024-08-19 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0015_alter_bairro_area_km2_alter_bairro_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecampanha',
            name='bairro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='cego47700.bairro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividadecampanha',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='cego47700.regiao'),
        ),
    ]
