# Generated by Django 5.0 on 2024-08-19 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0016_atividadecampanha_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadecampanha',
            name='agendado_por',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='cego47700.equipe'),
            preserve_default=False,
        ),
    ]
