# Generated by Django 5.0 on 2024-08-19 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0017_atividadecampanha_agendado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoMaterial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_aplicacao', models.CharField(choices=[('Comite', 'Comite'), ('Pre-Posto', 'Pre-posto'), ('Acao', 'Acao'), ('Externo', 'Externo')], default='Comite', max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('foto_aplicao', models.ImageField(blank=True, null=True, upload_to='acao_fotos/')),
                ('criado', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cego47700.materialcampanha')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cego47700.equipe')),
            ],
        ),
    ]
