# Generated by Django 5.0 on 2024-08-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cego47700', '0018_aplicacaomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcoesRealizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanoGoverno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
